# Generated by Django 3.1.7 on 2021-05-05 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=100)),
                ('region', models.IntegerField(null=True)),
                ('longitude', models.CharField(max_length=20, null=True)),
                ('latitude', models.CharField(max_length=20, null=True)),
                ('sampling', models.CharField(max_length=50)),
                ('public', models.CharField(max_length=250)),
                ('timetable', models.CharField(blank=True, max_length=250)),
                ('checkapp', models.CharField(blank=True, max_length=100)),
                ('phoneapp', models.IntegerField(blank=True)),
                ('webapp', models.CharField(blank=True, max_length=250)),
                ('restricted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth', models.DateField()),
                ('isvac', models.BooleanField()),
                ('vacdate', models.DateField()),
                ('center_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='covdm.center')),
            ],
        ),
    ]
